server:
  port: 8189
  servlet:
    context-path: /rest
response:
  exceptions:
    needStack: false
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: spring-rest
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./spring-rest/database;MODE=PostgreSQL
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
    open-in-view: false
  flyway:
    url: jdbc:h2:file:./spring-rest/database;MODE=PostgreSQL
    user: sa
    password: password
  h2:
    console:
      enabled: true
